{application,mon,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{mon_app,[]}},
              {env,[]},
              {modules,[mon_app,mon_db,mon_http,mon_reloader,mon_sup,
                        mon_users]}]}.
